import 'package:flutter/material.dart';

const icon_General = "assets/icons/icon_general.svg";
const icon_Bills = "assets/icons/icon_bills.svg";
const icon_calendar = "assets/icons/icon_calendar.svg";
const icon_calendar_selected = "assets/icons/icon_calendar_selected.svg";
const icon_entertainment = "assets/icons/icon_entertainment.svg";
const icon_grocery = "assets/icons/icon_grocery.svg";
const icon_insights = "assets/icons/icon_insights.svg";
const icon_person = "assets/icons/icon_person.svg";
const icon_person_selected = "assets/icons/icon_person_selected.svg";
const icon_shopping = "assets/icons/icon_shopping.svg";
const icon_transport = "assets/icons/icon_transport.svg";
const background = "assets/images/background.svg";
const icon_broadcastmessage = "assets/icons/broadcast.svg";
const icon_maintenance="assets/icons/maintenance.svg";
const icon_complaint="assets/icons/complaint.svg";
const icon_payment="assets/icons/payment.svg";
const icon_statement="assets/icons/statement.svg";
const icon_information="assets/icons/information.svg";